### ISSUE TITLE
DAVIS Dataset

### ISSUE THREAD

**Issue by waqarkaleemkhan** [cansyl/MDeePred#1]
Davis and filtered Davis dataset link of dropbox is not working can you please look to the link you have given in Read me file i need that urgenty please

**Comment by ahmetrifaioglu** [comment]
Dear @waqarkaleemkhan,

Thank you for your interest in MDeePred. The link has just been updated. Sorry for the inconvenience. 

Kind regards

**Comment by waqarkaleemkhan** [comment]
@ahmetrifaioglu Thank you soo much sir for your quick response.
