### ISSUE TITLE
Could you provide the target_feature_vector files for kinome data?

### ISSUE THREAD

**Issue by solanoon** [cansyl/MDeePred#2]
Hello, I would like to reproduce your experiment on the ChEMBL v27 dataset and I noticed that the link of target feature vectors files for the 12369 kinase data points was not provided. I wonder if it is possible for you to provide a link? Thank you so much.

**Comment by ahmetrifaioglu** [comment]
Dear @solanoon,

Thank you very much for your interest in MDeePred and we are sorry for the late reply. We uploaded the feature vectors for the kinase dataset. The download link and the training command are available on our GitHub page.

**Comment by solanoon** [comment]
Dear @ahmetrifaioglu,

Thank you very much for your kindly response.
I have downloaded your newly uploaded feature vectors for kinase data and tried to reproduce your experiment on them, but found that there are only around 252 proteins' features were provided, which is smaller than the protein number that claimed in the paper (329). 

I wonder whether there was a mis-uploading or should I just use the 252 proteins to reproduce your work.

**Comment by ahmetrifaioglu** [comment]
Dear @solanoon ,

I am sorry that I missed your last comment. I have just uploaded the correct file.

Best
