### ISSUE TITLE
could you please provide the code for generating protein feature vector?

### ISSUE THREAD

**Issue by ardejani** [cansyl/MDeePred#3]
Hello, 

I am interested in testing MDeePred with new protein sequences and I am wondering how to generate feature vectors for a new protein sequence from the AAindex matrices. I can't locate the part of the code that can do this. Could you please direct me to the code that can generate feature vectors for a new protein sequence from the AAindex matrices? 

Thanks

**Comment by ahmetrifaioglu** [comment]
Hi @ardejani,

We are sorry for the late response. The script ("**_static_file_generation.py_**") to generate feature matrices for protein sequences is now available under the **bin** folder. 

For each dataset, the target protein sequence file (i.e. "**target.fasta**") should be placed under "**helper_files**" folder of the corresponding dataset. Subsequently, "**save_separate_flattened_sequence_matrices**" function under the "**static_file_generation**" module can be used to create target feature matrix files. This function has three main parameters which are the name of dataset, the sequence length and name of the aaindex matrix. Sample function calls to create input feature matrices for Davis dataset are given below:

_save_separate_flattened_sequence_matrices("Davis", 500)
save_separate_flattened_sequence_matrices("Davis", 500, "ZHAC000103.txt")
save_separate_flattened_sequence_matrices("Davis", 500, "GRAR740104.txt")
save_separate_flattened_sequence_matrices("Davis", 500, "SIMK990101.txt")
save_separate_flattened_sequence_matrices("Davis", 500, "blosum62.txt")_

If you want to create feature matrices for a new fasta file, then you may create a dataset folder under "**training_files**" folder following the same structure and create your own feature matrices using a similar way as above.

**Comment by ardejani** [comment]
Thanks very much for your thorough response. I will try this asap and let you know...
