### ISSUE TITLE
Issues with the kinome data files 

### ISSUE THREAD

**Issue by ardejani** [cansyl/MDeePred#4]
Hi,

Thanks for making MDeePred. It's a great work again!

I encountered some issues with the data files  when I was trying to reproduce the kinome results. The protein IDs in the dti_datasets don't match the target_feature_vectors. Also, there are some files missing in the target_feature_vectors directories, such as Q9NQU5.

It would be great if you could fix this inconsistency.

Cheers,

Maz.

**Comment by ardejani** [comment]
I just noticed the missing files issue was mentioned previously but is not addressed _Originally posted by @solanoon in https://github.com/cansyl/MDeePred/issues/2#issuecomment-788565276_

**Comment by ahmetrifaioglu** [comment]
Hi @ardejani ,

Thank you for the warning. I have just realized that I uploaded another dataset file. The link has been corrected. Sorry for the inconvinience. 

Best
